// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionalRecipeBook.Domain;

#nullable disable

namespace NutritionalRecipeBook.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208110032_Move rating to comment entity")]
    partial class Moveratingtocommententity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.NutrientIngredient", b =>
                {
                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("IngredientAmountPer100G")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NutrientId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("NutrientIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IngredientAmountPer100G = 10m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IngredientAmountPer100G = 11m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IngredientAmountPer100G = 12m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IngredientAmountPer100G = 13m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            IngredientAmountPer100G = 14m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            IngredientAmountPer100G = 15m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            IngredientAmountPer100G = 16m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            IngredientAmountPer100G = 17m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            IngredientAmountPer100G = 18m
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            IngredientAmountPer100G = 19m
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 50m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 75m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 100m,
                            UnitOfMeasureId = new Guid("80000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.ShoppingListIngredient", b =>
                {
                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ShoppingListId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ShoppingListIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 1m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 2m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 3m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 4m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 5m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 6m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 7m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 8m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 9m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 10m,
                            Unit = "L"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.UserRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRecipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000000"),
                            IsFavourite = true,
                            IsOwner = true,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            IsFavourite = false,
                            IsOwner = false,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            IsFavourite = false,
                            IsOwner = true,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            IsFavourite = true,
                            IsOwner = false,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            IsFavourite = false,
                            IsOwner = true,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            IsFavourite = false,
                            IsOwner = false,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            IsFavourite = true,
                            IsOwner = true,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000007"),
                            IsFavourite = false,
                            IsOwner = false,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000008"),
                            IsFavourite = false,
                            IsOwner = true,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000009"),
                            IsFavourite = true,
                            IsOwner = false,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Content = "Comment 1 by UserName1 on Recipe 1",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 50, 31, 640, DateTimeKind.Utc).AddTicks(8),
                            Rating = 2,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Content = "Comment 2 by UserName2 on Recipe 2",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 40, 31, 640, DateTimeKind.Utc).AddTicks(17),
                            Rating = 3,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Content = "Comment 3 by UserName3 on Recipe 3",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 30, 31, 640, DateTimeKind.Utc).AddTicks(19),
                            Rating = 4,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Content = "Comment 4 by UserName4 on Recipe 4",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 20, 31, 640, DateTimeKind.Utc).AddTicks(21),
                            Rating = 5,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Content = "Comment 5 by UserName5 on Recipe 5",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 10, 31, 640, DateTimeKind.Utc).AddTicks(54),
                            Rating = 1,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Content = "Comment 6 by UserName6 on Recipe 6",
                            CreatedAt = new DateTime(2025, 12, 8, 10, 0, 31, 640, DateTimeKind.Utc).AddTicks(57),
                            Rating = 2,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Content = "Comment 7 by UserName7 on Recipe 7",
                            CreatedAt = new DateTime(2025, 12, 8, 9, 50, 31, 640, DateTimeKind.Utc).AddTicks(60),
                            Rating = 3,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            Content = "Comment 8 by UserName8 on Recipe 8",
                            CreatedAt = new DateTime(2025, 12, 8, 9, 40, 31, 640, DateTimeKind.Utc).AddTicks(62),
                            Rating = 4,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            Content = "Comment 9 by UserName9 on Recipe 9",
                            CreatedAt = new DateTime(2025, 12, 8, 9, 30, 31, 640, DateTimeKind.Utc).AddTicks(63),
                            Rating = 5,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            Content = "Comment 10 by UserName10 on Recipe 10",
                            CreatedAt = new DateTime(2025, 12, 8, 9, 20, 31, 640, DateTimeKind.Utc).AddTicks(67),
                            Rating = 1,
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsLiquid = false,
                            Name = "Ingredient 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsLiquid = true,
                            Name = "Ingredient 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsLiquid = false,
                            Name = "Ingredient 3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsLiquid = true,
                            Name = "Ingredient 4"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            IsLiquid = false,
                            Name = "Ingredient 5"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            IsLiquid = true,
                            Name = "Ingredient 6"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            IsLiquid = false,
                            Name = "Ingredient 7"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            IsLiquid = true,
                            Name = "Ingredient 8"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            IsLiquid = false,
                            Name = "Ingredient 9"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            IsLiquid = true,
                            Name = "Ingredient 10"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nutrients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Protein",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "Carbohydrate",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Fat",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "Fiber",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "Sugar",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Name = "Sodium",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Name = "Vitamin C",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Name = "Iron",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Name = "Calcium",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Name = "Potassium",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CaloriesPerServing")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CookingTimeInMin")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 20,
                            Description = "Description for recipe 1.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 1.",
                            Name = "Recipe 1",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 25,
                            Description = "Description for recipe 2.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 2.",
                            Name = "Recipe 2",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 30,
                            Description = "Description for recipe 3.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 3.",
                            Name = "Recipe 3",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 35,
                            Description = "Description for recipe 4.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 4.",
                            Name = "Recipe 4",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 40,
                            Description = "Description for recipe 5.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 5.",
                            Name = "Recipe 5",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 45,
                            Description = "Description for recipe 6.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 6.",
                            Name = "Recipe 6",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 50,
                            Description = "Description for recipe 7.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 7.",
                            Name = "Recipe 7",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 55,
                            Description = "Description for recipe 8.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 8.",
                            Name = "Recipe 8",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 60,
                            Description = "Description for recipe 9.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 9.",
                            Name = "Recipe 9",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            CaloriesPerServing = 0m,
                            CookingTimeInMin = 65,
                            Description = "Description for recipe 10.",
                            ImageUrl = "",
                            Instructions = "Instructions for recipe 10.",
                            Name = "Recipe 10",
                            Servings = 3
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShoppingLists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "UserName1's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "UserName2's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "UserName3's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "UserName4's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "UserName5's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "UserName6's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "UserName7's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "UserName8's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "UserName9's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "UserName10's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLiquidMeasure")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            IsLiquidMeasure = false,
                            Name = "g"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            IsLiquidMeasure = false,
                            Name = "kg"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            IsLiquidMeasure = true,
                            Name = "ml"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            IsLiquidMeasure = true,
                            Name = "l"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000005"),
                            IsLiquidMeasure = false,
                            Name = "tsp"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            IsLiquidMeasure = false,
                            Name = "tbsp"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000007"),
                            IsLiquidMeasure = true,
                            Name = "tsp"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000008"),
                            IsLiquidMeasure = true,
                            Name = "tbsp"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30b4923d-7331-4502-9eec-be1e3987c7b0",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name1",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname1",
                            TwoFactorEnabled = false,
                            UserName = "UserName1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ec29dc2-3d02-41a9-a211-b5474b9fc5a3",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name2",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname2",
                            TwoFactorEnabled = false,
                            UserName = "UserName2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0451793-a05e-45f8-bcd6-f37382390bce",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name3",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname3",
                            TwoFactorEnabled = false,
                            UserName = "UserName3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f56cc8c-0611-4f4c-9a09-0198dd7bd997",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name4",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname4",
                            TwoFactorEnabled = false,
                            UserName = "UserName4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec061913-2c0e-4892-9a7f-97c8d9e56360",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name5",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname5",
                            TwoFactorEnabled = false,
                            UserName = "UserName5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d5bfe3d-c273-459f-a5f3-3dbe5cf38d70",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name6",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname6",
                            TwoFactorEnabled = false,
                            UserName = "UserName6"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40c04eb4-35aa-4d91-92cc-f55d83d55d3f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name7",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname7",
                            TwoFactorEnabled = false,
                            UserName = "UserName7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60d4cf36-6545-47ca-a212-fabd9a60bbdc",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name8",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname8",
                            TwoFactorEnabled = false,
                            UserName = "UserName8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "096cad25-a735-4ae2-825a-cba8dfcf9843",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name9",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname9",
                            TwoFactorEnabled = false,
                            UserName = "UserName9"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9fa44b04-0b2f-4b99-a362-b00a0090b752",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Name10",
                            PhoneNumberConfirmed = false,
                            Surname = "Surname10",
                            TwoFactorEnabled = false,
                            UserName = "UserName10"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.NutrientIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("NutrientIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Nutrient", "Nutrient")
                        .WithMany("NutrientIngredients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.RecipeIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.ShoppingListIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.UserRecipe", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("UserRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Comment", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithOne("ShoppingList")
                        .HasForeignKey("NutritionalRecipeBook.Domain.Entities.ShoppingList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("NutrientIngredients");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingListIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Nutrient", b =>
                {
                    b.Navigation("NutrientIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ShoppingList")
                        .IsRequired();

                    b.Navigation("UserRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
