// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionalRecipeBook.Domain;

#nullable disable

namespace NutritionalRecipeBook.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.NutrientIngredient", b =>
                {
                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IngredientAmountPer100G")
                        .HasColumnType("int");

                    b.HasKey("NutrientId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("NutrientIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            IngredientAmountPer100G = 10
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            IngredientAmountPer100G = 11
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            IngredientAmountPer100G = 12
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            IngredientAmountPer100G = 13
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            IngredientAmountPer100G = 14
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            IngredientAmountPer100G = 15
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            IngredientAmountPer100G = 16
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            IngredientAmountPer100G = 17
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            IngredientAmountPer100G = 18
                        },
                        new
                        {
                            NutrientId = new Guid("30000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            IngredientAmountPer100G = 19
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 50m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 75m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 100m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 50m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 75m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 100m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 50m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 75m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 100m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 50m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 75m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 100m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 50m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 75m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 100m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 50m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 75m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 100m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 50m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 75m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 100m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 50m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 75m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 100m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 50m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 75m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 100m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 50m,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 75m,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 100m,
                            Unit = "ml"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.ShoppingListIngredient", b =>
                {
                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ShoppingListId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ShoppingListIngredients", (string)null);

                    b.HasData(
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 1m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 2m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 3m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 4m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 5m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 6m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 7m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 8m,
                            Unit = "L"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 9m,
                            Unit = "kg"
                        },
                        new
                        {
                            ShoppingListId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IngredientId = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 10m,
                            Unit = "L"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.UserRecipe", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserRecipes", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            IsFavourite = true,
                            IsOwner = true,
                            Rating = 1
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            IsFavourite = false,
                            IsOwner = false,
                            Rating = 2
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            IsFavourite = false,
                            IsOwner = true,
                            Rating = 3
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            IsFavourite = true,
                            IsOwner = false,
                            Rating = 4
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            IsFavourite = false,
                            IsOwner = true,
                            Rating = 5
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            IsFavourite = false,
                            IsOwner = false,
                            Rating = 1
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            IsFavourite = true,
                            IsOwner = true,
                            Rating = 2
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000008"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            IsFavourite = false,
                            IsOwner = false,
                            Rating = 3
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000009"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            IsFavourite = false,
                            IsOwner = true,
                            Rating = 4
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000010"),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            IsFavourite = true,
                            IsOwner = false,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Content = "Comment 1 by User1 on Recipe 1",
                            CreatedAt = new DateTime(2025, 11, 11, 9, 11, 11, 371, DateTimeKind.Utc).AddTicks(9948),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000001"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Content = "Comment 2 by User2 on Recipe 2",
                            CreatedAt = new DateTime(2025, 11, 11, 9, 1, 11, 371, DateTimeKind.Utc).AddTicks(9965),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000002"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Content = "Comment 3 by User3 on Recipe 3",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 51, 11, 371, DateTimeKind.Utc).AddTicks(9970),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000003"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Content = "Comment 4 by User4 on Recipe 4",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 41, 11, 371, DateTimeKind.Utc).AddTicks(9974),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000004"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Content = "Comment 5 by User5 on Recipe 5",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 31, 11, 371, DateTimeKind.Utc).AddTicks(9979),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000005"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Content = "Comment 6 by User6 on Recipe 6",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 21, 11, 371, DateTimeKind.Utc).AddTicks(9985),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000006"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Content = "Comment 7 by User7 on Recipe 7",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 11, 11, 371, DateTimeKind.Utc).AddTicks(9990),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000007"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            Content = "Comment 8 by User8 on Recipe 8",
                            CreatedAt = new DateTime(2025, 11, 11, 8, 1, 11, 371, DateTimeKind.Utc).AddTicks(9995),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000008"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            Content = "Comment 9 by User9 on Recipe 9",
                            CreatedAt = new DateTime(2025, 11, 11, 7, 51, 11, 372, DateTimeKind.Utc),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000009"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            Content = "Comment 10 by User10 on Recipe 10",
                            CreatedAt = new DateTime(2025, 11, 11, 7, 41, 11, 372, DateTimeKind.Utc).AddTicks(6),
                            RecipeId = new Guid("40000000-0000-0000-0000-000000000010"),
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLiquid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            IsLiquid = false,
                            Name = "Ingredient 1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            IsLiquid = true,
                            Name = "Ingredient 2"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            IsLiquid = false,
                            Name = "Ingredient 3"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            IsLiquid = true,
                            Name = "Ingredient 4"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            IsLiquid = false,
                            Name = "Ingredient 5"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            IsLiquid = true,
                            Name = "Ingredient 6"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            IsLiquid = false,
                            Name = "Ingredient 7"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            IsLiquid = true,
                            Name = "Ingredient 8"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            IsLiquid = false,
                            Name = "Ingredient 9"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            IsLiquid = true,
                            Name = "Ingredient 10"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nutrients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "Protein",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "Carbohydrate",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "Fat",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "Fiber",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "Sugar",
                            Unit = "g"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Name = "Sodium",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Name = "Vitamin C",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Name = "Iron",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Name = "Calcium",
                            Unit = "mg"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Name = "Potassium",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CookingTimeInMin")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CookingTimeInMin = 20,
                            Description = "Description for recipe 1.",
                            Instructions = "Instructions for recipe 1.",
                            Name = "Recipe 1",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CookingTimeInMin = 25,
                            Description = "Description for recipe 2.",
                            Instructions = "Instructions for recipe 2.",
                            Name = "Recipe 2",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CookingTimeInMin = 30,
                            Description = "Description for recipe 3.",
                            Instructions = "Instructions for recipe 3.",
                            Name = "Recipe 3",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CookingTimeInMin = 35,
                            Description = "Description for recipe 4.",
                            Instructions = "Instructions for recipe 4.",
                            Name = "Recipe 4",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CookingTimeInMin = 40,
                            Description = "Description for recipe 5.",
                            Instructions = "Instructions for recipe 5.",
                            Name = "Recipe 5",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CookingTimeInMin = 45,
                            Description = "Description for recipe 6.",
                            Instructions = "Instructions for recipe 6.",
                            Name = "Recipe 6",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            CookingTimeInMin = 50,
                            Description = "Description for recipe 7.",
                            Instructions = "Instructions for recipe 7.",
                            Name = "Recipe 7",
                            Servings = 3
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            CookingTimeInMin = 55,
                            Description = "Description for recipe 8.",
                            Instructions = "Instructions for recipe 8.",
                            Name = "Recipe 8",
                            Servings = 4
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            CookingTimeInMin = 60,
                            Description = "Description for recipe 9.",
                            Instructions = "Instructions for recipe 9.",
                            Name = "Recipe 9",
                            Servings = 2
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            CookingTimeInMin = 65,
                            Description = "Description for recipe 10.",
                            Instructions = "Instructions for recipe 10.",
                            Name = "Recipe 10",
                            Servings = 3
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShoppingLists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "User1's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "User2's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "User3's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "User4's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "User5's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "User6's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "User7's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "User8's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "User9's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "User10's Shopping List",
                            UserId = new Guid("00000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Username = "User5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Username = "User6"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Username = "User7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Username = "User8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Username = "User9"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Username = "User10"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.NutrientIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("NutrientIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Nutrient", "Nutrient")
                        .WithMany("NutrientIngredients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.RecipeIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.ShoppingListIngredient", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.ConnectionTables.UserRecipe", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("UserRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Comment", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("NutritionalRecipeBook.Domain.Entities.User", "User")
                        .WithOne("ShoppingList")
                        .HasForeignKey("NutritionalRecipeBook.Domain.Entities.ShoppingList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("NutrientIngredients");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingListIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Nutrient", b =>
                {
                    b.Navigation("NutrientIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListIngredients");
                });

            modelBuilder.Entity("NutritionalRecipeBook.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ShoppingList")
                        .IsRequired();

                    b.Navigation("UserRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
